### PR TITLE
internal: downgrade required CMake version

### PR DESCRIPTION
**Pull request by Pospelove**

### CODE REVIEW

**Review by Darkwood9612 — APPROVED** [review]

**Comment by nic11** [comment]
`cmake_minimum_required` left in `skyrim-platform/src/platform_se/CMakeLists.txt`

**Comment by nic11** [comment]
Another note: Linux build succeeded on CMake 3.18.1 too (but I didn't clean vcpkg cache, maybe some deps fail, I can check that later)

**Comment by Pospelove** [comment]
`skymp5-server/cmake-js-fetch/CMakeLists.txt` is technically top-level project (invoked by npm that is being invoked by cmake)
leaving minimal required version here

**Comment by nic11** [comment]
Yep, this seems good. I had warning when I removed that too

**Pull request merged**
