### PR TITLE
fix(skymp5-front): remove debug checkbox, fix Github and Patreon buttons, add debug checking for onClick property

### LINKED ISSUE #354: Remove debug checkbox from top-left

### PR DESCRIPTION
**Pull request by vladdenisov**
Closes #354 and #357

### CODE REVIEW

**Comment by Pospelove** [comment]
Hey! Could you please fix the formatting

**Comment by vladdenisov** [comment]
We also need to fix `alt` property for images maybe, but I think it's not a big deal while this property is basically for screen readers.

**Comment by Pospelove** [comment]
@vladdenisov I mean https://github.com/skyrim-multiplayer/skymp/blob/cbd828770b278af2350c860e5d63edd3904b1d48/skymp5-front/src/constructor.js#L76

**Comment by vladdenisov** [comment]
> @vladdenisov I mean
> 
> https://github.com/skyrim-multiplayer/skymp/blob/cbd828770b278af2350c860e5d63edd3904b1d48/skymp5-front/src/constructor.js#L76

oops, i forgot this, i'll fix this soon

**Comment by Pospelove** [comment]
@vladdenisov Thanks for the PR, sorry for the delay, I'm going to integrate this by myself

**Pull request merged**
