### PR TITLE
internal: add prettier & .editorconfig

### LINKED ISSUE #1293: Prettier TS formatting check in CI

### PR DESCRIPTION
**Pull request by Korisss**
closes #1293

### CODE REVIEW

**Comment by Korisss** [comment]
you can look at the individual commits with .prettierrc.json and .editorconfig without formatted files if formatted files bother you

**Comment by VitaliyMubarakov** [comment]
Super ficha srazu v prod ❤️❤️

**Comment by Pospelove** [comment]
@Korisss How do I run prettier locally?

**Comment by Korisss** [comment]
> @Korisss How do I run prettier locally?

You need to install prettier in root dir via ’ yarn‘ and run prettier with ’ yarn prettier-format’. You also can use prettier vs code extension, but this requires installed prettier

**Comment by Pospelove** [comment]
@Korisss could you please submit a PR without actual reformatting? I'll accept and then reformat.

**Comment by Korisss** [comment]
@Pospelove it will be hard after the merge, but i will do it

**Comment by Pospelove** [comment]
@Korisss could you please also add prettier to this workflow: https://github.com/skyrim-multiplayer/skymp/blob/main/.github/workflows/reformat.yml

It reformats c++ code when see commit with [reformat] tag

**Comment by Korisss** [comment]
It might not work, but in theory it should

**Pull request merged**
