### PR TITLE
fix(skymp5-client): NPC appear unexpectedly

### PR DESCRIPTION
**Pull request by Pospelove**
See your bugs channel in Discord
Someone reports this bug in Riften jarl house

### CODE REVIEW

**Comment by Pospelove** [comment]
image

**Comment by Pospelove** [comment]
@SupAidmi people complain. I think this fix may help

**Comment by SupAidmi** [comment]
> g

Your PR has already been checked, the fix is working. When preparing the next update for release, it will be merged and added to the client.

**Comment by Pospelove** [comment]
> Your PR has already been checked, the fix is working. When preparing the next update for release, it will be merged and added to the client.

Thanks for your answer

**Comment by reveriadive** [comment]
Rather than this.. it's much more stable if you change FindRandomActor to FindClosestActor.
Fixes pop-ins and equipment sync.

I have a pull request that will be going up soon for that.

**Comment by Pospelove** [comment]
> Rather than this.. it's much more stable if you change FindRandomActor to FindClosestActor. Fixes pop-ins and equipment sync.
> 
> I have a pull request that will be going up soon for that.

Hey! Thanks for this, can't wait for your PR, it's amazing if you got this to work

**Review by nic11 — APPROVED** [review]

**Review by nic11 — APPROVED** [review]

**Pull request merged**
