### PR TITLE
fix(skyrim-platform): fix crash in combatState event

### LINKED ISSUE #1544: [Bug]: CTD when reloading a save while in combat after registering a combatState event
### Severity

Critical. A critical defect that causes some key functionality to fail.

### Priority

High. Anything that impacts the typical user flow or blocks app usage.

### Description

If a combatState event was registered, I observed a CTD when reloading a save before the NPC appeared during a fight with an NPC after a hostile random NPC appeared.
(The CTD did not occur if the save was reloaded after the battle with the NPC ended.)

NetScriptFramework Crash Log: https://drive.google.com/file/d/1YL84AYcA02xc0-5l5rfdpi_jHf1ELcVQ/view?usp=sharing

https://github.com/skyrim-multiplayer/skymp/issues/1305
https://github.com/skyrim-multiplayer/skymp/issues/1540
The phenomenon is similar to the save reload CTD reported elsewhere.

Even if the combatState event registration was canceled at the time the preLoadGame event occurred, a CTD would still occur, and the CTD could not be prevented unless the event registration was canceled at the time before the preLoadGame event occurred.
Also, loading a save saved from the menu before the NPC appeared caused a CTD, but loading a save saved by pressing F5 did not.
(F5 saves are set to regular saves instead of quick saves in the SSE Engine Fixes configuration file.)

### OS

Windows

### OS version

10

### Skyrim version

1.5.97.0.8

### SKSE version

2.0.20

### client commit''s hash

None

### server commit''s hash

None

### Videocard model

Radeon RX 590

### Steps to reproduce

With the combatState event registered, perform the following steps.

1. Save from the system menu by pressing ESC, either externally or internally. (Do not press F5 to save).
2. Type "player.placeatme 0001bcd8 5" in the console and a random NPC will appear. (They are bandits, so they will be hostile as they appear.)
3. Reload the save for step 1 after confirming that the bandits have been hostile.

### Expected result

No crashes after loading the save.

### Actual result

The game crashes as soon as the loading completes.

### PR DESCRIPTION
**Pull request by objir**
Follow the example of the fix for #1305.

closes #1544

### CODE REVIEW

**Review by Pospelove — CHANGES_REQUESTED** [review]
please also reformat with clang-format and add add changelog file here https://github.com/skyrim-multiplayer/skymp/tree/main/docs/release/dev

**Review by Pospelove — CHANGES_REQUESTED** [review]
thanks! clang format and we're good to go

btw you can reformat file in VS (ctrl+K+D as I remember)

**Comment by objir** [comment]
> thanks! clang format and we're good to go
> 
> btw you can reformat file in VS (ctrl+K+D as I remember)

Is [this](https://github.com/objir/skymp/commit/be1150cede21a1c9e39d5447248246130cea4d7c) ok?

**Review by Pospelove — APPROVED** [review]

**Comment by Pospelove** [comment]
Thanks for the PR!

**Pull request merged**
