### PR TITLE
refact: move records to separate files & apply common espm-related fixes

### LINKED ISSUE #1244: Fix some invalid const-casts in lib_espm
See `TODO(#1244)` comments. Maybe something else if you spot it

### PR DESCRIPTION
**Pull request by che6a**
closes #1244

### CODE REVIEW

**Review by Pospelove — APPROVED** [review]

**Comment by Pospelove** [comment]
please port https://github.com/skyrim-multiplayer/skymp/commit/6b61dd64c54e52450ce6a4f43b19a6c7c98b6e85 properly

**Comment by che6a** [comment]
@Pospelove

**Review by Pospelove — APPROVED** [review]

**Comment by Pospelove** [comment]
We will test on indev for 3 days.

**Comment by Pospelove** [comment]
@che6a please fix conflicts again and i will merge

**Review by Pospelove — APPROVED** [review]

**Pull request merged**
