### PR TITLE
feat(skymp5-server): don't allow downloading of esm/esp files

### PR DESCRIPTION
**Pull request by nic11**

### CODE REVIEW

**Comment by nic11** [comment]
Made this a draft until we check on the test server

**Comment by Korisss** [comment]
Please add also esl (another plugin format)

**Review by Pospelove — CHANGES_REQUESTED** [review]
Please add .bsa to your regex and then I gonna approve

In the past we used that mechanism to empower our launchers: skymp5-launcher was able to download required esp and even bsa files. Hardcoding for now is OK, but hope we will be able to add config option for allowing esp download or not.

**Comment by nic11** [comment]
Hmm, I don't understand how we're going to have .bsa files... but I guess we'll use it some day (again?), so here we go...

**Comment by nic11** [comment]
Decided to make it another line for readability

**Review by Pospelove — APPROVED** [review]

**Pull request merged**
