### PR TITLE
feat(skymp5-client): send changed attribute percentages to the server

### LINKED ISSUE #189: Send changed attribute percentages every 1s to the server
Use `getActorValuePercentage` on the player, send only if changed.

### PR DESCRIPTION
**Pull request by q1000treadz**
close #189

### CODE REVIEW

**Review by Pospelove — CHANGES_REQUESTED** [review]
1. Please format your code with `Right Mouse Button => Format` in vscode
2. Use `===` instead of `==`.
3. Send every 1s, not with other sends

**Review by Pospelove — CHANGES_REQUESTED** [review]
In this implementation, the client floods to the server even if the player keeps 100% health value. We should 
1. never send unchanged values.
2. send changes not more often than 1 per second

please say if i didn't understand your code correctly

**Review by Pospelove — APPROVED** [review]

**Review by alekcey0211 — CHANGES_REQUESTED** [review]
1. Change let to const if variable doesn’t change

**Comment by Pospelove** [comment]
@alekcey0211 Thanks for your comment. You are right!
But unfortunately, we can't break our dev process to stop at this. PR's author decided to use the `let` keyword and check the `ac` variable more than one time. And I decided to approve these changes. Your pull request fixing this will be welcome. I also think we can set up eslint in our CI.

**Pull request merged**
