### PR TITLE
internal: add package.json and yarn.lock to server dist

### LINKED ISSUE #613: Add package.json and yarn.lock to server dist

### PR DESCRIPTION
**Pull request by nic11**
Closes #613

### CODE REVIEW

**Comment by Pospelove** [comment]
Hope it works for Sup and Aidme

**Comment by nic11** [comment]
@SupAidmi Please check that `npx yarn` can be run right after downloading dist and unpacking server to a clean folder

**Review by Pospelove — APPROVED** [review]
LGTM. Requires approve from SupAidme to merge

**Review by Pospelove — CHANGES_REQUESTED** [review]
it will always install node modules twice.
`bat` file shouldn't reinstall if we compiled the server on this machine

**Review by Pospelove — APPROVED** [review]

**Pull request merged**
