### PR TITLE
feat(skymp5-scripts): update SweetPie scripts

### PR DESCRIPTION
**Pull request by nic11**
Authored by Artemio

### CODE REVIEW

**Review by Pospelove — APPROVED** [review]

**Comment by nic11** [comment]
WTF why doesn't GH rerun CI?

**Comment by Pospelove** [comment]
I don't know. BTW we usually ignore CI when it doesn't work well.

**Comment by nic11** [comment]
Ok, I guess we can merge then...

**Review by Pospelove — APPROVED** [review]

**Comment by nic11** [comment]
Hmm it doesn't check merged commit too... I guess GH is somewhat broken right now

**Pull request merged**
