### PR TITLE
feat(skymp5-server): update sweetpiescript ids

### PR DESCRIPTION
**Pull request by che6a**

### CODE REVIEW

**Review by Pospelove — APPROVED** [review]

**Comment by Pospelove** [comment]
todo: merge after Ansgar test

**Comment by Pospelove** [comment]
needs Ansgar/Aidmi approval (they want add more ids or smth)

**Review by Pospelove — APPROVED** [review]

**Comment by che6a** [comment]
@Pospelove

**Review by Pospelove — APPROVED** [review]

**Comment by Pospelove** [comment]
I think we can test it in game

**Pull request merged**
