### PR TITLE
internal: add Ubuntu build CI check

### LINKED ISSUE #588: Use Docker for running CI on Linux

### PR DESCRIPTION
**Pull request by nic11**
Closes #588

### CODE REVIEW

**Comment by nic11** [comment]
A few issues exist with this. Nevertheless, it's quite ready for the actual CI in my opinion.
1. GH appears to have no possibility to upload a `.tar.gz` artifact and it wraps EVERYTHING to a `.zip`. So I guess no good solution here, have to choose between `.tar.gz.zip` and `.tar.zip` :/ Regular zip would also work, but artifact uploading drops executable bits (even though they are supported). See https://github.com/actions/upload-artifact/issues/39
2. #164 is still unfixed, so it makes dist unusable yet (unless we add some hack to dev_service or somewhere else). But this PR is still useful, because i) it checks build itself, ii) once `libChakraCore.so` is delivered some other way to the target machine, we're good to go
3. Some strange error occurs in Windows build, couldn't understand what goes wrong quick enough, you may have more ideas here
4. For some reason, I couldn't manage `ctest` to actually print what `unit` executable itself prints (even though it's the same the invocation as in Windows PR yaml), so I've left just `./unit/unit` call for now. Maybe you've got some ideas on what's wrong here: https://github.com/skyrim-multiplayer/skymp/runs/4402294906?check_suite_focus=true

**Comment by Pospelove** [comment]
4. https://github.com/skyrim-multiplayer/skymp/blob/52bd31ced417d99e2a980c8183833d659dc3793a/cmake/run_test_unit.cmake#L16

Try adding `if(WIN32)` before `skymp_execute_process` to get CTest to work. It's Win-only OpenCppCoverage stuff. Or you can print `${STDOUT}` of `skymp_execute_process` and hack `skymp_execute_process` itself.

**Comment by Pospelove** [comment]
Hope we fix #374 in the future. Hardcoding SVG names is sick.

**Review by Pospelove — APPROVED** [review]

**Comment by Pospelove** [comment]
Will fix (4) in a separate issue

**Comment by Pospelove** [comment]
P.s. win build fail is tracked in https://github.com/skyrim-multiplayer/skymp/issues/600

**Pull request merged**
