### PR TITLE
internal: prettier format

### PR DESCRIPTION
**Pull request by shevernitskiy**
We use clang-formatter for c++ file uniformity. I suggest adding formatting to ts, js, json, md and various  other project files using Prettier.

[https://prettier.io/](https://prettier.io/)

Extensions for major popular IDEs are available. 

Further it is possible to add formatting check to Formatting Check Workflow.

I propose to take the settings in `.prettierrc.yml`

### CODE REVIEW

**Comment by Pospelove** [comment]
well, let's add ci check then

**Comment by nic11** [comment]
Just a note for future: I also want `.editorconfig` to be in main: #983

**Comment by nic11** [comment]
Oh no... it makes too much stuff different from existing code style

**Comment by shevernitskiy** [comment]
you can suggest other settings if preserving the current style is important

**Comment by Pospelove** [comment]
Thanks but closing for now. We will probably get back to this in the future.

**Pull request closed without merging**
