### PR TITLE
feat(skymp5-client): specific animation system

### PR DESCRIPTION
**Pull request by kkEngine**
- specific animation system

### CODE REVIEW

**Review by Pospelove — CHANGES_REQUESTED** [review]
skymp5-client isn't a right place to add SweetPie-specific features

Please consider creating a property in gamemode skymp5-functions-lib
example:
https://github.com/skyrim-multiplayer/skymp/blob/main/skymp5-functions-lib/src/props/disableCheats.ts

**Comment by SupAidmi** [comment]
> skymp5-client isn't a right place to add SweetPie-specific features
> 
> Please consider creating a property in gamemode skymp5-functions-lib example: https://github.com/skyrim-multiplayer/skymp/blob/main/skymp5-functions-lib/src/props/disableCheats.ts

We will definitely remove it from the client later when the game mod developer has some free time. If you want, you can implement this through the game mode soon.

**Comment by Pospelove** [comment]
@kkEngine @SupAidmi Fixed. Feel free to revert/overwrite my commit if it is not needed. Please let me know if I should create a new PR instead.

**Review by Wedmer — APPROVED** [review]

**Comment by Pospelove** [comment]
will keep working in #1404 (technical issue with pushing to kkEngine remote)

**Pull request closed without merging**
