### PR TITLE
docs: OnHit and damage calculation

### PR DESCRIPTION
**Pull request by nic11**

### CODE REVIEW

**Comment by Pospelove** [comment]
@nic11 I think we should only document what's present in our implementation. There are issues for potential improvements.

**Review by Pospelove — APPROVED** [review]

**Comment by Pospelove** [comment]
Approved. Feel free to add something if it is needed.

**Comment by nic11** [comment]
I will take a look when I have a bit more time to do it

**Comment by Pospelove** [comment]
Dinakrab says there is a bug in our formula (both in docs and implementation). Merging as it is for further fixes in both places.

**Pull request merged**
