### PR TITLE
internal: refactor chakracore portfile

### PR DESCRIPTION
**Pull request by Pospelove**
This PR is created to sync ChakraCore portfile with vcpkg PR https://github.com/microsoft/vcpkg/pull/22439

### CODE REVIEW

**Review by nic11 — APPROVED** [review]

**Review by nic11 — CHANGES_REQUESTED** [review]
Hmm, what about the other files?

**Comment by Pospelove** [comment]
I plan to land this PR when vcpkg PR will be merged

**Comment by Pospelove** [comment]
well. ok, I'll update vcpkg.json. it isn't strictly required for overlay_ports however

**Comment by nic11** [comment]
Oh, it's the only one, I see

**Comment by Pospelove** [comment]
Merging this in the hope to help you with #607 and heat our CI
If smth changes in the final vcpkg's version of the port, I'll sync it in further pull requests

**Comment by nic11** [comment]
@Pospelove Changes from #607 were already pushed to DockerHub actually

**Pull request merged**
