### PR TITLE
internal: introduce formatting checks

### PR DESCRIPTION
**Pull request by nic11**

### CODE REVIEW

**Comment by Pospelove** [comment]
https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests/

**Comment by nic11** [comment]
> we could enforce code formatting instead of failing workflow

I don't think it's a must-have. Person who merges can always see if all checks have passed.

**Comment by Pospelove** [comment]
> > we could enforce code formatting instead of failing workflow
> 
> I don't think it's a must-have. Person who merges can always see if all checks have passed.

It's extremely useful in case we need to merge some important patches right now, but they are not properly formatted.

**Comment by nic11** [comment]
> > > we could enforce code formatting instead of failing workflow
> > 
> > 
> > I don't think it's a must-have. Person who merges can always see if all checks have passed.
> 
> It's extremely useful in case we need to merge some important patches right now, but they are not properly formatted.

You mean it's better to enforce it even though it will delay merging? Checks can always be fixed separately

**Comment by Pospelove** [comment]
@nic11 is it ready for review?

**Comment by nic11** [comment]
Yep, it's ready

**Comment by Pospelove** [comment]
Thanks!

**Pull request merged**
