### PR TITLE
fix(skymp5-server): incorrect weapon hit cooldown

### LINKED ISSUE #440: [WIP][Bug]: Incorrect weapon hit cooldown
### Severity

Major. A crucial error that indicates a deviation from business logic or disrupts the program, but doesn't have a vital impact on the app.

### Priority

Medium. Anything that negatively affects the user experience.

### Description

Weapon cooldown is longer than the attack animation time, by about 30%

### OS

Windows

### OS version

10

### Skyrim version

1.5,97,08

### SKSE version

2.0.20

### client commit''s hash

4920b7887dc4d4d2bafae48586e77aeb1eee9603

### server commit''s hash

4920b7887dc4d4d2bafae48586e77aeb1eee9603

### Videocard model

RX 470

### Steps to reproduce

Player 1 attacks player 2 with any weapon several attacks in a row

### Expected result

Each hit deals damage

### Actual result

Each second hit deals damage

See video & cooldown diagram (two-handed weapon)

https://drive.google.com/file/d/1w01iGQAYVYZZEpLoCbOc8nngOVZRCoKs/view?usp=sharing
https://drive.google.com/file/d/1m8OSz1qtVK0QS1ftUyo8Zu5HROG2s6-T/view?usp=sharing

Cooldown

### PR DESCRIPTION
**Pull request by d0gge**
Closes #440

### CODE REVIEW

**Comment by Pospelove** [comment]
This PR should be approved by @SupAidmi

**Review by SupAidmi — CHANGES_REQUESTED** [review]
Cooldown is correctly works with  onehanded weapons (dagger, sword, mace, axe), but still not for twohanded weapons (sword and hummer). The cooldown of twohanded sword ~ 1,3-1,5 sec (must be ~ 1,1 sec.) Cooldown of twohanded hammer and battle-axe ~ 1,5-1,7 sec (must be ~ 1,3 sec.)

May be we need to set for twohanded weapons separate value of cooldown

**Comment by Pospelove** [comment]
@d0gge Take anim type from DNAM 

0=Other, 1=OneHandSword, 2=OneHandDagger, 3=OneHandAxe, 4=OneHandMace, 5=TwoHandSword, 6=TwoHandAxe, 7=Bow, 8=Staff, 9=Crossbow

So if anim type is 5 or 6, then use another multiplier.
For other anim types please keep the previous version.

See also https://en.uesp.net/wiki/Skyrim_Mod:Mod_File_Format/WEAP

**Comment by nic11** [comment]
@Pospelove @d0gge I think this should be 'fix' rather than 'feat'

**Review by SupAidmi — APPROVED** [review]
Cooldown works fine now

**Comment by Pospelove** [comment]
Thanks to you all, glad this feature finally works!

**Pull request merged**
