### PR TITLE
internal: add missing header

### PR DESCRIPTION
**Pull request by Korisss**
Without this fix I have an error
изображение

### CODE REVIEW

**Comment by Pospelove** [comment]
internal*

**Review by nic11 — APPROVED** [review]

**Comment by Korisss** [comment]
> internal*

```
- internal - fixes or changes in the build system, catalog structure, or anything that doesn't execute on the user's machine.
```
Why internal? These changes are not in the build system or project structure.

**Comment by Pospelove** [comment]
build fix. anyway nic11 decides

**Comment by nic11** [comment]
Well... it's not like it's a runtime bug. This include falls under "anything that doesn't execute on the user's machine" I guess, so

**Comment by nic11** [comment]
But overall I think it should be refactored so that we have a constant like this:
```cpp
constexpr std::string_view kPexExtension{".pex"};
```
and then use `kPexExtension.length()` instead of this `strlen` that can execute again every time (although it's probably optimised out)

**Pull request merged**
